#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
import sys
import json

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# module_uuid of the mailserver binded
mail_server= data['mail_server']
mail_hostname = data['mail_hostname']
agent.set_env("MAIL_SERVER",mail_server)
agent.set_env("MAIL_HOSTNAME",mail_hostname)
