#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Configure traefik route for sftpgo webui

import os
import sys
import json
import agent

data = json.load(sys.stdin)

localuser = data["localuser"]
agent.run_helper("systemctl", "--user", "start", "imapsync@"+localuser).check_returncode()
