#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

data = json.load(sys.stdin)

localuser = data["localuser"]
agent.run_helper("run-imapsync", "start", localuser).check_returncode()
