#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json

data = json.load(sys.stdin)
# Local user to sync on
localuser = data["localuser"]
# remote credentials
remotehostname = data["remotehostname"]
remoteport = data["remoteport"]
remoteusername = data["remoteusername"]
remotepassword = data["remotepassword"]

# security encryption tls,ssl,""
security = data.get("security",'')
if security == "tls":
    security = "--tls1"
elif security == "ssl":
    security = "--ssl1"
else:
    security = ""

# delete on local host folder/emails not on remote
delete = data.get("delete",False)
if delete:
    delete = "--delete2"
    delete_folder = "--delete2foders"
else:
    delete = ""
    delete_folder = ""

# exclude file if string,string2 or trashsync == disabled
exclude = data.get("exclude",'')
trashsync= data.get("trashsync",False)
exclude = exclude.split(',')
if exclude != "":
    exclude = '|'.join(exclude)
if not trashsync:
    exclude = exclude + '|^Trash|^Deleted Items' 

user_env = f"""
LOCALUSER={localuser}
REMOTEUSERNAME={remoteusername}
REMOTEHOSTNAME={remotehostname}
REMOTEPORT={remoteport}
SECURITY={security}
DELETE={delete}
DELETEFOLDER={delete_folder}
EXCLUDE={exclude}
"""
os.umask(0o77)

f = open("./imapsync/"+localuser+".env", "w", encoding="utf-8")
f.write(user_env)
f.close()

f = open("./imapsync/"+localuser+".pwd", "w", encoding="utf-8")
f.write(remotepassword)
f.close()
