#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import glob
import agent

for file in glob.iglob("imapsync/*.env"):
    localuser = file.removeprefix('imapsync/').removesuffix('.env')
    agent.run_helper("run-imapsync", "stop", localuser).check_returncode()
