#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "MAIL_SERVER",
        "MAIL_HOST"
    ]:
     agent.set_env(evar, original_environment[evar])
