#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.s
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

if event['module_uuid'] == os.getenv('MAIL_SERVER', ''):
   # Restart to apply changed settings
   rdb = agent.redis_connect()

   # retrieve mail module_hostname from module_uuid
   mail_server = os.environ["MAIL_SERVER"]
   providers = agent.list_service_providers(rdb, 'imap', 'tcp', {
      'module_uuid': mail_server,
   })
   mail_host = providers[0]["mail_host"]
   agent.set_env("MAIL_HOST",mail_host)
   agent.run_helper("systemctl", "--user", "try-restart", "imapsync.service").check_returncode()
